version: "3"
services:
  nginx:
    build: ./docker/nginx
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./public:/usr/share/nginx/html
      ports: ["10080:10080"]
  app:
    build: ./ruby
      volumes:
        - ./ruby:/ruby
        - ./public:/public
     command: bundle exec rackup -p 8000 -o 0.0.0.0
      ports: ["18000:8000"]
      environment: 
        MYSQL_HOST: mysql
  mysql:
    build: ./docker/mysql
    ports: ["13306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
